# Generated by Django 4.1.10 on 2023-08-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Villet1', '0002_villetuser_aadhar_villetuser_anninc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villetuser',
            name='userpass',
        ),
    ]
