# Generated by Django 4.1.10 on 2023-08-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Villet1', '0003_remove_villetuser_userpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villetuser',
            name='pan',
            field=models.CharField(default=0, max_length=328),
        ),
    ]
