# Generated by Django 4.1.10 on 2023-08-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Villet1', '0005_alter_villetuser_aadhar_alter_villetuser_anninc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCreditCard',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=70)),
                ('active_numberAV', models.IntegerField(default=0)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=9)),
                ('credit_score', models.IntegerField(default=600)),
                ('credit_points', models.IntegerField(default=300)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('last_bill_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VUTransaction',
            fields=[
                ('transaction_id', models.PositiveIntegerField(default=2000, primary_key=True, serialize=False)),
                ('Transaction_Name', models.CharField(default=0, max_length=100)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(default=0, max_length=30)),
                ('Receiver_Account_Number', models.CharField(default=0, max_length=30)),
                ('Villet_Credit_Card_Number', models.CharField(default=0, max_length=30)),
                ('Periodic_Transaction', models.CharField(default=0, max_length=30)),
                ('Duration', models.CharField(default=0, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='villetuser',
            name='active_number',
            field=models.IntegerField(default=0),
        ),
    ]
