# Generated by Django 4.1.10 on 2023-08-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Villet1', '0006_activecreditcard_vutransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vutransaction',
            name='transaction_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
