# Generated by Django 4.1.10 on 2023-08-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Villet1', '0007_alter_vutransaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vutransaction',
            name='transaction_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
