# Generated by Django 4.1.10 on 2023-08-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Villet1', '0008_alter_vutransaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vutransaction',
            name='active',
            field=models.CharField(default='active', max_length=30),
        ),
    ]
