# Generated by Django 4.1.10 on 2023-09-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Villet1', '0009_vutransaction_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='activecreditcard',
            name='Bill_paid',
            field=models.IntegerField(default=0),
        ),
    ]
