# Generated by Django 4.1.10 on 2023-09-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Villet1', '0011_activecreditcard_new_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villetuser',
            name='aadhar',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='villetuser',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
